#!/usr/bin/env bash
set -e # halt script on error

git config --global user.name "Travis CI"
git config --global user.email "$COMMIT_AUTHOR_EMAIL"

bundle exec jekyll build
#bundle exec htmlproofer ./_site --disable-external
