#!/usr/bin/env bash
set -e # halt script on error

git config user.name "Travis CI"
git config user.email "$COMMIT_AUTHOR_EMAIL"

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external

# If there are no changes to the compiled out (e.g. this is a README update) then just bail.
if git diff --quiet; then
    echo "No changes to the output on this push; exiting."
    exit 0
fi

bundle exec rake deploy
